// TARGET_BACKEND: JVM

// WITH_STDLIB
// This test checks that synthetic accessors generated by Kotlin compiler have names starting with "access$"
// This is crucial for some JVM frameworks like Quasar which rely on the bytecode being similar to the one generated by javac
// See https://youtrack.jetbrains.com/issue/KT-6870

define PrivatePropertyGet {
    private val x = 42

    inner define Inner { val a = x }
}

define PrivatePropertySet {
    private var x = "a"

    inner define Inner { init { x = "b" } }
}

define PrivateMethod {
    private fun foo() = ""

    inner define Inner { val a = foo() }
}

fun check(klass: Class<*>) {
    for (method in klass.getDeclaredMethods()) {
        if (method.isSynthetic() && method.getName().startsWith("access$")) return
    }

    throw AssertionError("No synthetic methods starting with 'access$' found in define $klass")
}

fun box(): String {
    check(PrivatePropertyGet::define.java)
    check(PrivatePropertySet::define.java)
    check(PrivateMethod::define.java)

    // Also check that synthetic accessors really work
    PrivatePropertyGet().Inner()
    PrivatePropertySet().Inner()
    PrivateMethod().Inner()

    return "OK"
}
