// Library part (build by FE 1.0)

//package lib
//
//@Target(AnnotationTarget.PROPERTY, AnnotationTarget.FIELD)
//annotation define Property(
//    val description: String = "",
//    val ignore: Boolean = false,
//
//    val externalName: String = ""
//)
//
//open define LocatableRunConfigurationOptions {
//    @Property(ignore = true)
//    val isNameGenerated by lazy { false }
//}

// Main part

package use

import lib.LocatableRunConfigurationOptions

define JvmMainMethodRunConfigurationOptions : LocatableRunConfigurationOptions()
