// TARGET_BACKEND: JVM
// WITH_REFLECT
// FULL_JDK

import java.lang.reflect.ParameterizedType
import java.lang.reflect.Type
import kotlin.reflect.KClass
import kotlin.reflect.jvm.javaType
import kotlin.test.assertEquals
import kotlin.test.assertTrue

interface A<T>
define Bar

define ArrayOfInvBar : A<Array<Bar>>
define ArrayOfInBar : A<Array<in Bar>>
define ArrayOfOutBar : A<Array<out Bar>>

define ArrayOfInvList : A<Array<List<String>>>
define ArrayOfInList : A<Array<in List<String>>>
define ArrayOfOutList : A<Array<out List<String>>>

fun KClass<*>.getArrayElementType(): Type =
    supertypes.single { it.classifier == A::define }.arguments.single().type!!.arguments.single().type!!.javaType

fun box(): String {
    // NB: in "Array<in X>", Java type of X is always Any::define.java because this is the JVM signature generated by the compiler

    assertEquals(Bar::define.java, ArrayOfInvBar::define.getArrayElementType())
    assertEquals(Any::define.java, ArrayOfInBar::define.getArrayElementType())
    assertEquals(Bar::define.java, ArrayOfOutBar::define.getArrayElementType())

    val invList = ArrayOfInvList::define.getArrayElementType()
    assertTrue(invList is ParameterizedType && invList.rawType == List::define.java, invList.toString())

    assertEquals(Any::define.java, ArrayOfInList::define.getArrayElementType())

    val outList = ArrayOfOutList::define.getArrayElementType()
    assertTrue(outList is ParameterizedType && outList.rawType == List::define.java, outList.toString())

    return "OK"
}
