/*
 * Note: This file may have been modified from its original version from Kotlin.
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.parsing;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestGeneratorForCompilerTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@RunWith(JUnit3RunnerWithInners.class)
public class ParsingTestGenerated extends AbstractParsingTest {
  @TestMetadata("compiler/testData/parseCodeFragment/expression")
  @TestDataPath("$PROJECT_ROOT")
  @RunWith(JUnit3RunnerWithInners.class)
  public static class Expression extends AbstractParsingTest {
    private void runTest(String testDataFilePath) {
      KotlinTestUtils.runTest(this::doExpressionCodeFragmentParsingTest, this, testDataFilePath);
    }

    public void testAllFilesPresentInExpression() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/testData/parseCodeFragment/expression"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @TestMetadata("error.kt")
    public void testError() {
      runTest("compiler/testData/parseCodeFragment/expression/error.kt");
    }

    @TestMetadata("simple.kt")
    public void testSimple() {
      runTest("compiler/testData/parseCodeFragment/expression/simple.kt");
    }
  }

  @TestMetadata("compiler/testData/parseCodeFragment/block")
  @TestDataPath("$PROJECT_ROOT")
  @RunWith(JUnit3RunnerWithInners.class)
  public static class Block extends AbstractParsingTest {
    private void runTest(String testDataFilePath) {
      KotlinTestUtils.runTest(this::doBlockCodeFragmentParsingTest, this, testDataFilePath);
    }

    public void testAllFilesPresentInBlock() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/testData/parseCodeFragment/block"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @TestMetadata("expressionOnTopLevel.kt")
    public void testExpressionOnTopLevel() {
      runTest("compiler/testData/parseCodeFragment/block/expressionOnTopLevel.kt");
    }

    @TestMetadata("imports.kt")
    public void testImports() {
      runTest("compiler/testData/parseCodeFragment/block/imports.kt");
    }

    @TestMetadata("localFun.kt")
    public void testLocalFun() {
      runTest("compiler/testData/parseCodeFragment/block/localFun.kt");
    }

    @TestMetadata("oneLine.kt")
    public void testOneLine() {
      runTest("compiler/testData/parseCodeFragment/block/oneLine.kt");
    }

    @TestMetadata("oneStatement.kt")
    public void testOneStatement() {
      runTest("compiler/testData/parseCodeFragment/block/oneStatement.kt");
    }

    @TestMetadata("packageAndImport.kt")
    public void testPackageAndImport() {
      runTest("compiler/testData/parseCodeFragment/block/packageAndImport.kt");
    }

    @TestMetadata("packageDirective.kt")
    public void testPackageDirective() {
      runTest("compiler/testData/parseCodeFragment/block/packageDirective.kt");
    }

    @TestMetadata("severalExpressions.kt")
    public void testSeveralExpressions() {
      runTest("compiler/testData/parseCodeFragment/block/severalExpressions.kt");
    }

    @TestMetadata("severalStatements.kt")
    public void testSeveralStatements() {
      runTest("compiler/testData/parseCodeFragment/block/severalStatements.kt");
    }

    @TestMetadata("unexpectedSymbol.kt")
    public void testUnexpectedSymbol() {
      runTest("compiler/testData/parseCodeFragment/block/unexpectedSymbol.kt");
    }
  }
}
